floyd.cpp, prims.cpp
Please review my pull request I've added Floyd Warshall algorithm class.
=> Added floyd warshall algorithm class in C++

Array_Stack.cpp, Linked_Stack.cpp
=> Added Stack implementations

Quick_sort_algorithm.cpp
Added Quick Sort Algorithm in cpp @Amisha-here
=> Added Quick Sort Algorithm in cpp

README.md
Following things are included in Readme file:
1. Added definition and  some types of Data structure.
2.Added definition and some type of Algorithms.
=> Made README.md file

permutation_of_string.cpp
Please review my PR. I have added code of Permutation of a string using backtracking.
=> Added permutation_of_string.cpp

bfs_map.cpp, prims.cpp
Review my pull request added Prims algorithm class in C++
=> Added Prims algorithm class

merge_sort.cpp
I have added merge sort using recursion.
=> added merge_sort.cpp

README.md, bubble-sort.cpp, linear-search.cpp
Added linear search algorithm solution in cpp.
=> Linear search

README.md, bubble-sort.cpp
Added Bubble sort Algorithm solution in CPP.
=> Bubble sort

N Queen Problem.cpp
Added code of N Queen Problem in C++
=> Create N Queen Problem.cpp

transitiveclosure.cpp
Algorithm for Transitive closure of graph
=> graph algorithm.

Shell_Sort
C++ code for Shell Sort Algorithm
=> Shell_Sort

palindrome_number.cpp, topologicalsort.cpp
Please review my Topological Sort program in C++
=> Topological Sort program C++

Bubble-Sort.cpp, Find_BST_In_Binary_Tree.cpp
Hope that u will Consider it For Merging.I want to Contribute More so if U(@Amisha-here) find it Useful,Reply..
Thanks in Advance!.
=> Added Code Finding Largest Binary Search Tree in Binary Tree

prefix_sum.cpp, prefix_sum_array.cpp
Added C++ class for prefix sum array
=> Added C++ class for prefix sum array

Find_Largest_BST_In_BinaryTree.cpp, Find_Unique_Number
This is the Minimum Time Comlexity Code(O(N)) For Finding Unique Number which has only one number one times and all the  remaining Numbers three times.
Hope U will consider it.I want to make more Contribution.Please Notify me.
Thanks in Advance||
=> Added Find_Unique_Number

Fractional Knapsack
Imolementation of Fractional Knapsack using cpp
=> Create Fractional Knapsack

Kahns_algo.cpp
Hey @Amisha-here , I am adding Kahn's algorithm. Please merge it and also please the hacktober fest label to it. Thanks!!!
=> Kahn's algorithm

kruskalAlgorithm.cpp
Hope you find it valuable to Merge
=> Added Kruskal Algorithm in Cpp

Prim's algorithm for finding MST
=> Prims algorithm C++ implementation

Dijkstra’s_shortest_path_algorithm.cpp
Added Dijkstra’s shortest path algorithm
=> Added Dijkstra’s shortest path algorithm

reverse_LinkedList.cpp
Added program to reverse a singly linked list in C++. Happy Learning, Kudos to your work!
=> Reverse a LinkedList

Juggling_Algo.(Array_Rotation).cpp
This algorithm helps to rotate an array by a given number of time .This question asked in Amazon and other companies interview.
=> Juggling_Algorithm.cpp

cirq.c
=> Added Circular queue for C

uglyno.cpp
=> Added uglyno with dp

dutchflag.cpp
dutchflag problem to sort an array having three types of elements only.
=> DUTCH FLAG ALGO

Dynamic Programming/0-1Knapsack.cpp, Dynamic Programming/subset-given-set.cpp, Dynamic Programming/subset-sum.cpp, kahn-algo.cpp
**Kahn algorithm** for cycle detection and **dynamic programming** folder having 3 famous problems of DP **0-1 Knapsack**, **subset-sum problem**, **subset with given sum problem**.
**Thanks in advance!**
=> Kahn algorithm and dynamic folder

Dynamic Programming/DP puzzle/area-choice.cpp, Dynamic Programming/DP puzzle/dice-throw.cpp, Dynamic Programming/DP puzzle/egg-dropping.cpp, Dynamic Programming/DP puzzle/tiles-stack.cpp, Dynamic Programming/coin-change.cpp, Dynamic Programming/cut-rod.cpp, Dynamic Programming/fibo.cpp
3 more programs of **dynamic programming** and a **folder of DP puzzles** having a standard set of puzzles on DP are added.
=> Dynamic programming puzzle added

circular_queue.cpp
program to display the working of the circular queue using cpp.
=> circular_queue.cpp

Array Intersection.cpp, Merge Sort.cpp
I am a participant of Hacktoberfest 2021. Kindly review and merge this branch or please label it as 'hacktoberfest-accepted' . Thank You !!
Question : Print the intersection of two given arrays.
Solution : The solution is in C++ language.
=> Added Array Intersection.cpp

Bipartite-graph.cpp
Hi can I add algorithm to check if graph is Bipartite or not?
=> Bipartite graphs

Dynamic Programming/longest_increasing_subsequence_dp.cpp
Bottom-Up DP solution of Longest Increasing Subsequence problem
=> Created longest_increasing_subsequence_dp.cpp

Dynamic Programming/matrix_chain_multiplication.cpp
Hello. I am adding a popular DP problem matrix chain multiplication to the DP folder.
=> adding matrix chain multiplictaion in dp folder

rabin_karp_algo_pattern_match.cpp
C++ program to match string patterns using Rabin Karp algorithm
=> New code rabin_karp_algo_pattern_match.cpp

KMP_String_Matching_Algorithm.cpp
I have added the C++ Program for Knuth Morris Pratt (KMP) String Matching Algorithm
=> C++ Program for KMP String Matching Algorithm Added

datascraper.py, intro_to_graphics.cpp
Merge it and label it with tag "hacktoberfest-accepted" if you will like it.
Thank you in advance
=> This intro_to_graphics.cpp is a code for basic graphics work

Hailstone Sequence.cpp
Please accept this as hacktoberfest-accepted label.
=> Added Hailstone Sequence.cpp

linkedList.js
I'm use Java Script for create linked list and methods for help in algorithm learning
=> create linkedlist in JS
